### ISSUE TITLE
Milestone 1 work

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/normtestPY#1]
- [x] Summary paragraph project on high level (coste)
- [x] Contributing (richie)
- [x] Code of Conduct (coste)
- [x] Finish setting up directory structure (sylvia)

Each person for their function:
- [x] Write empty function and function documentation (everyone)
- [x] Test for each package (everyone)
- [x] Document test functions (everyone)
- [x] Research other similar packages (everyone)
